// jROOT Tools library master  01 Jun 2020
#include <j_clipboard_parse.h>
#include <j_effpeaks.h>
#include <j_elements.h>
#include <j_env.h>
#include <j_extra_guitools.h>
#include <j_filecustodian.h>
#include <j_fitholder.h>
#include <j_fitting.h>
#include <j_gate_subtract.h>
#include <j_gating_frame.h>
#include <j_gating_select_frame.h>
#include <j_gating_tool.h>
#include <j_gpad_tools.h>
#include <j_hist_formatting.h>
#include <j_spectool.h>
#include <j_treetup_tool.h>
#include <j_ultrafit_env.h>
#include <j_ultrapeakfit.h>
#include <j_ultrapeak.h>
#include <j_utility.h>
#include <j_X11paste.h>
